// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_team_metrics from './routes/api/[team]/metrics.ts';
import * as $api_jobs from './routes/api/jobs.ts';
import * as $api_jobs_job_ from './routes/api/jobs/[job].ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $api_users from './routes/api/users.ts';
import * as $backend_team_year_month_day_ from './routes/backend/[team]/[year]/[month]/[day].tsx';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $index from './routes/index.tsx';
import * as $version from './routes/version.ts';
import * as $weekly_pull_request_summary_table from './islands/weekly-pull-request-summary-table.tsx';
import * as $weekly_task_summary_table from './islands/weekly-task-summary-table.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/api/[team]/metrics.ts': $api_team_metrics,
		'./routes/api/jobs.ts': $api_jobs,
		'./routes/api/jobs/[job].ts': $api_jobs_job_,
		'./routes/api/joke.ts': $api_joke,
		'./routes/api/users.ts': $api_users,
		'./routes/backend/[team]/[year]/[month]/[day].tsx':
			$backend_team_year_month_day_,
		'./routes/greet/[name].tsx': $greet_name_,
		'./routes/index.tsx': $index,
		'./routes/version.ts': $version,
	},
	islands: {
		'./islands/weekly-pull-request-summary-table.tsx':
			$weekly_pull_request_summary_table,
		'./islands/weekly-task-summary-table.tsx': $weekly_task_summary_table,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
