// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_team_metrics from './routes/api/[team]/metrics.ts';
import * as $api_jobs from './routes/api/jobs.ts';
import * as $api_jobs_job_ from './routes/api/jobs/[job].ts';
import * as $api_joke from './routes/api/joke.ts';
import * as $api_users from './routes/api/users.ts';
import * as $backends_team_ from './routes/backends/[team].tsx';
import * as $backends_team_year_month_ from './routes/backends/[team]/[year]/[month].tsx';
import * as $backends_team_year_month_day_ from './routes/backends/[team]/[year]/[month]/[day].tsx';
import * as $backends_team_year_month_pull_requests from './routes/backends/[team]/[year]/[month]/pull-requests.tsx';
import * as $backends_team_year_month_tasks from './routes/backends/[team]/[year]/[month]/tasks.tsx';
import * as $doc from './routes/doc.tsx';
import * as $greet_name_ from './routes/greet/[name].tsx';
import * as $index from './routes/index.tsx';
import * as $teams from './routes/teams.tsx';
import * as $version from './routes/version.ts';
import * as $team_list_container from './islands/team-list-container.tsx';
import * as $weekly_pull_request_summary_table from './islands/weekly-pull-request-summary-table.tsx';
import * as $weekly_standings from './islands/weekly-standings.tsx';
import * as $weekly_task_summary_table from './islands/weekly-task-summary-table.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
	routes: {
		'./routes/_404.tsx': $_404,
		'./routes/_app.tsx': $_app,
		'./routes/api/[team]/metrics.ts': $api_team_metrics,
		'./routes/api/jobs.ts': $api_jobs,
		'./routes/api/jobs/[job].ts': $api_jobs_job_,
		'./routes/api/joke.ts': $api_joke,
		'./routes/api/users.ts': $api_users,
		'./routes/backends/[team].tsx': $backends_team_,
		'./routes/backends/[team]/[year]/[month].tsx':
			$backends_team_year_month_,
		'./routes/backends/[team]/[year]/[month]/[day].tsx':
			$backends_team_year_month_day_,
		'./routes/backends/[team]/[year]/[month]/pull-requests.tsx':
			$backends_team_year_month_pull_requests,
		'./routes/backends/[team]/[year]/[month]/tasks.tsx':
			$backends_team_year_month_tasks,
		'./routes/doc.tsx': $doc,
		'./routes/greet/[name].tsx': $greet_name_,
		'./routes/index.tsx': $index,
		'./routes/teams.tsx': $teams,
		'./routes/version.ts': $version,
	},
	islands: {
		'./islands/team-list-container.tsx': $team_list_container,
		'./islands/weekly-pull-request-summary-table.tsx':
			$weekly_pull_request_summary_table,
		'./islands/weekly-standings.tsx': $weekly_standings,
		'./islands/weekly-task-summary-table.tsx': $weekly_task_summary_table,
	},
	baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
